### ISSUE TITLE
For a new CI4 project

### ISSUE THREAD

**Issue by salain** [lonnieezell/codigniter-shield#2]
Hi Lonnie, 
Is this repo a replacement for Myth-auth?
I am starting a new CI4 project, can this package be use instead of myth-auth.

Thank you

**Comment by lonnieezell** [comment]
It is not anywhere close to complete. But feel free to keep an eye on it :)

**Comment by nowackipawel** [comment]
Hi @lonnieezell ;-) how are you?
Could you please let us about an update? Is it in your opinion ready to use on production? ;-)

**Comment by lonnieezell** [comment]
I'm using it as I'm building out Bonfire and I think it's 99% there for production. There's one issue a user has reported with the "actions" (after login/registration optionals like 2FA and email verification. Those currently rely on it being in the session which probably not the right way to go with that.  Other than that I would call the code production ready.

Mostly what I have left on it is documention and see if I can make the onboarding process smoother with it.

**Comment by nowackipawel** [comment]
Thank you. It looks like gr8 piece of code.

**Comment by nowackipawel** [comment]
May you guys share Events config somehow? 
didLogin, didRegister, etc. ;-), there are calls to it but I cannot find them configured anywhere ;-)

**Comment by lonnieezell** [comment]
There's no configuration needed if you don't need to use it. If you do, just add it to your `Events` config file as described in the [user guide](https://codeigniter.com/user_guide/extending/events.html#defining-an-event). Something like: 

```php
Events::on('didLogin', function (...$params)
{
    // do stuff here
});
```

**Comment by nowackipawel** [comment]
> There's no configuration needed if you don't need to use it.

Ohh, that's ok. I was not sure if those events should fire something by default or not.

About: 

> Those currently rely on it being in the session which probably not the right way

What do you think about idea to simplify code in Register/LoginController:

It is:
```
$actionClass = setting('Auth.actions')['register'] ?? null;

        if (! empty($actionClass)) {
            session()->set('auth_action', $actionClass);

            return redirect()->to('auth/a/show');
        }
```
it could be:
```
        if (setting('Auth.actions')['register'] ?? null) {
            return redirect()->to('auth/a/show');
        }
```
and check class that should support it directly in ActionController?
